INSERT INTO food (id, name, category)
VALUES
/*fruits*/
(101, 'Apple', 'fruit'),
(102, 'Banana', 'fruit'),
(103, 'Orange', 'fruit'),
(104, 'Cherries', 'fruit'),
(105, 'Watermelon', 'fruit'),
(106, 'Cantelope', 'fruit'),
(107, 'Honeydew', 'fruit'),
(108, 'Clementine', 'fruit'),
(109, 'Green Grapes', 'fruit'),
(110, 'Red Grapes', 'fruit'),
(111, 'Mango', 'fruit'),
(112, 'Pineapple', 'fruit'),
(113, 'Blackberries', 'fruit'),
(114, 'Strawberries', 'fruit'),
(115, 'Blueberries', 'fruit'),
(116, 'Dates', 'fruit'),
(117, 'Grapefruit', 'fruit'),
(118, 'Kiwi', 'fruit'),
(119, 'Lime', 'fruit'),
(120, 'Lemon', 'fruit'),
(121, 'Papaya', 'fruit'),
(122, 'Necatrine', 'fruit'),
(123, 'Pear', 'fruit'),
(124, 'Peach', 'fruit'),
(125, 'Plantain', 'fruit'),
(126, 'Plum', 'fruit'),
(127, 'Pomegranate', 'fruit'),
(128, 'Raspberries', 'fruit'),
(129, 'Passion fruit', 'fruit'),
(130, 'Figs', 'fruit'),
(131, 'Raisins', 'fruit'),

/*vegetables*/
(201, 'Broccoli', 'vegetable'),
(202, 'Artichokes', 'vegetable'),
(203, 'Brussel Sprouts', 'vegetable'),
(204, 'Celery', 'vegetable'),
(205, 'Cucumber', 'vegetable'),
(206, 'Zucchini', 'vegetable'),
(207, 'Asparagus', 'vegetable'),
(208, 'Arugula', 'vegetable'),
(209, 'Bok Choy', 'vegetable'),
(210, 'Green Cabbage', 'vegetable'),
(211, 'Red Cabbage', 'vegetable'),
(212, 'Carrots', 'vegetable'),
(213, 'Cauliflower', 'vegetable'),
(214, 'Corn', 'vegetable'),
(215, 'Edamame', 'vegetable'),
(216, 'Eggplant', 'vegetable'),
(217, 'Fennel', 'vegetable'),
(218, 'Kale', 'vegetable'),
(219, 'Iceburg Lettuce', 'vegetable'),
(220, 'Romaine Lettuce', 'vegetable'),
(221, 'Mushrooms', 'vegetable'),
(222, 'Red Onion', 'vegetable'),
(223, 'Yellow Onion', 'vegetable'),
(224, 'Shallots', 'vegetable'),
(225, 'Scallions', 'vegetable'),
(226, 'Green Peas', 'vegetable'),
(227, 'Green Pepper', 'vegetable'),
(228, 'Red Pepper', 'vegetable'),
(229, 'Yellow Pepper', 'vegetable'),
(230, 'Russet Potato', 'vegetable'),
(231, 'Red Potato', 'vegetable'),
(232, 'Yellow Potato', 'vegetable'),
(233, 'Sweet Potato', 'vegetable'),
(234, 'Pumpkin', 'vegetable'),
(235, 'Radishes', 'vegetable'),
(236, 'Sugar Snap Peas', 'vegetable'),
(237, 'Spaghetti Squash', 'vegetable'),
(238, 'Spinach', 'vegetable'),
(239, 'Butternut Squash', 'vegetable'),
(240, 'Tomatoes', 'vegetable'),

/*Meat+Seafood*/
(301,'Ground Beef','meat/seafood'),
(302,'Bacon','meat/seafood'),
(303,'Turkey Bacon','meat/seafood'),
(304,'Chicken Breast','meat/seafood'),
(305,'Chicken Thigh','meat/seafood'),
(306,'Ground Turkey','meat/seafood'),
(307,'Steak','meat/seafood'),
(308,'Sliced Ham','meat/seafood'),
(309,'Sliced Turkey','meat/seafood'),
(310,'Salmon','meat/seafood'),
(311,'Shrimp','meat/seafood'),
(312,'Crab','meat/seafood'),
(313,'Sausage','meat/seafood'),
(314,'Chuck Roast','meat/seafood'),
(315,'Sirloin Steak','meat/seafood'),
(316,'Strip Steak','meat/seafood'),
(317,'Ribeye Steak','meat/seafood'),
(318,'T-Bone Steak','meat/seafood'),
(320,'Pork Chop','meat/seafood'),
(321,'Pork Sirloin','meat/seafood'),
(322,'Beef Tenderloin','meat/seafood'),
(323,'Ribs','meat/seafood'),
(324,'Scallops','meat/seafood'),
(325,'Salami','meat/seafood'),
(326,'Ribs','meat/seafood'),
(327,'Tuna','meat/seafood'),
(328,'Tuna Salad','meat/seafood'),
(329,'Chicken Salad','meat/seafood'),

/*dairy*/
(401, 'Milk', 'dairy'),
(402, 'Sour Cream', 'dairy'),
(403, 'Cheddar Cheese', 'dairy'),
(404, 'Motzerella Cheese', 'dairy'),
(405, 'Swiss Cheese', 'dairy'),
(406, 'Parmesan', 'dairy'),
(407, 'Milk', 'dairy'),

/*misc*/
(501, 'Hummus', 'misc'),
(502, 'Guacamole', 'misc'),
(503, 'Salsa', 'misc'),
(504, 'Salsa Verde', 'misc'),
(505, 'Jelly', 'misc'),
(506, 'Tzatziki', 'misc');





